### ISSUE TITLE
Appendix L "Streaming TTML Content" does not reflect best industry practice.

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml1#208]
Support for streaming pre-recorded content generally requires fragmentation of a larger document, possibly one for an entire piece of content. Industry practice fragmentation techniques, such as those described in EBU Tech 3381, are inconsistent with this. Suggest updating this Appendix to reflect best industry practice, or alternatively delete it (it is not cited in the Rec body).

**Comment by palemieux** [comment]
@mikedo @nigelmegitt Would copying Annex R from the current TTML2 draft (https://www.w3.org/TR/ttml2/#streaming) work?

**Comment by mikedo** [comment]
At least R.2 describes current actual practice (although I would have led with that over the theoretical R.1).  I'm glad that TTML2 is better now. The alternatives for fixing TTML1 are: remove the Annex; replicate the language of R.2; or informatively reference TTML2 R/R.2.  All of these, including replicating all of R, are acceptable to me. It's odd in general to have an Annex that is not referenced from the body (a condition forbidden in ISO/IEC fyi) which is why deleting it is equally OK with me.

**Comment by nigelmegitt** [comment]
@palemieux @mikedo I'm likewise happy to duplicate annex R from TTML2. In fact this was on my mind just yesterday and I would have proposed it if you hadn't! There's nothing about annex R.2 that doesn't apply equally to TTML1 as to TTML2. Some of the reference links e.g. to the term definition of ISD would need to be checked and somehow dealt with - ISD isn't defined in TTML1, though it would be an editorial refactoring to do so, and most likely an improvement.

I think TTML2 R.3 should be omitted though since there's no meaningful way defined by TTML1 to serialise an ISD.

**Comment by nigelmegitt** [comment]
> It's odd in general to have an Annex that is not referenced from the body (a condition forbidden in ISO/IEC fyi) which is why deleting it is equally OK with me.

I'm not aware of any W3C rules about this, and the information is useful, so I'd keep it. By the way I can't find a reference to appendix M Concrete Encoding either but I definitely wouldn't want to remove that!

I'd prefer to keep Appendix L, but essentially copy over appendix R from TTML2 minus R.3.

**Comment by palemieux** [comment]
> I'd prefer to keep Appendix L, but essentially copy over appendix R from TTML2 minus R.3.

+1
