### ISSUE TITLE
Clarify semantics of content bpd for inline and line areas.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml1#212]
Need an errata to add some default definition of content bpd (height in horizontal WMs) for inline areas and their relation to content bpd of line area. See also [1] and #209.

[1] [https://lists.w3.org/Archives/Public/public-tt/2016Apr/0007.html](https://lists.w3.org/Archives/Public/public-tt/2016Apr/0007.html)

**Comment by cconcolato** [comment]
Reading the minutes that talk about TTML2, it is unclear if this errata would make TTML1 more compatible to TTML2 or less. Can someone clarify?

**Comment by nigelmegitt** [comment]
It looks like the driver for this issue was to allow padding to be set consistently on spans so that the effect of `fillLineGap` can be generated. I think it's now clear that (browser) UAs do not in general use the same content area "height" and that even if they did, the solution to line gap filling might lie elsewhere. I'm not sure if we need to do this now - it may be better to wait for some feedback from CSS WG on the fill line gap issue before continuing with this. Any view on that @skynavga ?

**Comment by nigelmegitt** [comment]
WG F2F 2018-01-10: WG agrees to close since this issue is now with CSS WG and the behaviour is better understood now than when the issue was originally opened.
