### ISSUE TITLE
Unspecified font size can't fit a region extent if it's specified in pixels

### ISSUE THREAD

**Issue by fcartegnie** [w3c/ttml1#253]
https://github.com/w3c/ttml1/blob/446dc9b65bc1056b54c9e36da8690750aeca55ba/testsuite/Styling/Origin002.xml#L23

We have no idea what the 1c font size will finally be and if it will fit the extent.
see also #206

**Comment by nigelmegitt** [comment]
@fcartegnie in this example, that is correct, since there's no `tts:extent` on the `tt:tt` element, so you don't know what the cell resolution computes to in pixels. Some profiles require that the root container region extent is specified if pixel units are used anywhere, which helps to deal with this.

It may be worth using the [IMSC tests](https://github.com/w3c/imsc-tests) as a good starting point for implementation testing - I believe those tests are absent this kind of issue (though bugs have a way of finding their way in to any code!).

In this specific example, the implementation is expected to allocate some pixel size to the root container region, and at that point you can compute the pixel size of the cell. In other words, the results are different depending on, say, the video, or the video viewport (or whatever else the implementation uses to derive the root container region extent).

**Comment by fcartegnie** [comment]
To me that's the same problem.
The ISMC Extent002.ttml test can't also display properly as test result.
While the region has the right size, the text has no font size and probably can't fit/be displayed.

**Comment by nigelmegitt** [comment]
Sorry, no, that's not correct - the IMSC [Extent002.ttml](https://github.com/w3c/imsc-tests/blob/master/imsc1/ttml/extent/Extent002.ttml) test specifies the root container region extent as `tts:extent="320px 240px"` so you can calculate the value of 1c in all cases.

**Comment by palemieux** [comment]
@fcartegnie To expand on @nigelmegitt , `1c` is by default 1/15 of the root container height (15 rows), so `tts:fontSize='1c'` would be computed as 240/15 = 16 px in the case of https://github.com/w3c/imsc-tests/blob/master/imsc1/ttml/extent/Extent002.ttml .

Makes sense?

**Comment by palemieux** [comment]
@fcartegnie Looking forward to your feedback on the IMSC tests, by the way.

**Comment by fcartegnie** [comment]
I've modifed my code to apply column units to root extents instead of always applying to screen size.
ttml spec is always so easy to figure :/
thanks for the help then.

**Comment by palemieux** [comment]
> thanks for the help then.

Anytime!
